item {
  name : "speed_limit"
  id : 1
}
item {
  name : "mph"
  id : 2
}
item {
  name : "10 mph"
  id : 3
}
item {
  name : "15 mph"
  id : 4
}
item {
  name : "20 mph"
  id : 5
}
item {
  name : "25 mph"
  id : 6
}
item {
  name : "30 mph"
  id : 7
}
item {
  name : "35 mph"
  id : 8
}
item {
  name : "40 mph"
  id : 9
}
item {
  name : "45 mph"
  id : 10
}
item {
  name : "50 mph"
  id : 11
}
item {
  name : "55 mph"
  id : 12
}
item {
  name : "60 mph"
  id : 13
}
item {
  name : "65 mph"
  id : 14
}
item {
  name : "70 mph"
  id : 15
}
item {
  name : "75 mph"
  id : 16
}
item {
  name : "80 mph"
  id : 17
}
item {
  name : "85 mph"
  id : 18
}
item {
  name : "tree crown"
  id : 19
}
item {
  name : "car rear light"
  id : 20
}
item {
  name : "car"
  id : 21
}
item {
  name : "advertisement_board"
  id : 22
}
item {
  name : "roof"
  id : 23
}
item {
  name : "tire"
  id : 24
}
item {
  name : "lane_end_merge_left"
  id : 25
}
item {
  name : "lane_end_merge_right"
  id : 26
}
item {
  name : "merge_left"
  id : 27
}
item {
  name : "merge_right"
  id : 28
}
item {
  name : "Pedestrian_crossing"
  id : 29
}
item {
  name : "Road_construction"
  id : 30
}
item {
  name : "stop"
  id : 31
}
item {
  name : "traffic_light_ahead"
  id : 32
}
item {
  name : "TBD9"
  id : 33
}
item {
  name : "TBD10"
  id : 34
}
item {
  name : "TBD11"
  id : 35
}
item {
  name : "TBD12"
  id : 36
}
item {
  name : "TBD13"
  id : 37
}
item {
  name : "TBD14"
  id : 38
}
item {
  name : "TBD15"
  id : 39
}
item {
  name : "TBD16"
  id : 40
}
item {
  name : "TBD17"
  id : 41
}
item {
  name : "TBD18"
  id : 42
}
item {
  name : "TBD19"
  id : 43
}
item {
  name : "TBD20"
  id : 44
}
item {
  name : "TBD21"
  id : 45
}
item {
  name : "TBD22"
  id : 46
}
item {
  name : "TBD23"
  id : 47
}
item {
  name : "TBD24"
  id : 48
}
item {
  name : "TBD25"
  id : 49
}
item {
  name : "TBD26"
  id : 50
}
item {
  name : "TBD27"
  id : 51
}
item {
  name : "TBD28"
  id : 52
}
item {
  name : "TBD29"
  id : 53
}
item {
  name : "TBD30"
  id : 54
}
item {
  name : "TBD31"
  id : 55
}item {
  name : "TBD32"
  id : 56
}
item {
  name : "TBD33"
  id : 57
}
item {
  name : "TBD34"
  id : 58
}
item {
  name : "TBD35"
  id : 59
}
item {
  name : "TBD36"
  id : 60
}
item {
  name : "TBD37"
  id : 61
}
item {
  name : "TBD37"
  id : 62
}
item {
  name : "TBD38"
  id : 63
}
item {
  name : "TBD39"
  id : 64
}
item {
  name : "TBD40"
  id : 65
}
item {
  name : "TBD41"
  id : 66
}
item {
  name : "TBD42"
  id : 67
}
item {
  name : "TBD43"
  id : 68
}
item {
  name : "TBD44"
  id : 69
}
item {
  name : "TBD45"
  id : 70
}
item {
  name : "TBD46"
  id : 71
}
item {
  name : "TBD47"
  id : 72
}
item {
  name : "TBD48"
  id : 73
}
item {
  name : "TBD49"
  id : 74
}
item {
  name : "TBD50"
  id : 75
}
item {
  name : "TBD51"
  id : 76
}
item {
  name : "TBD52"
  id : 77
}
item {
  name : "TBD53"
  id : 78
}
item {
  name : "TBD54"
  id : 79
}
item {
  name : "TBD55"
  id : 80
}
item {
  name : "TBD56"
  id : 81
}
item {
  name : "TBD57"
  id : 82
}
item {
  name : "TBD58"
  id : 83
}
item {
  name : "TBD59"
  id : 84
}
item {
  name : "TBD60"
  id : 85
}
item {
  name : "TBD61"
  id : 86
}
item {
  name : "TBD62"
  id : 87
}
item {
  name : "TBD63"
  id : 88
}
item {
  name : "TBD64"
  id : 89
}
item {
  name : "TBD65"
  id : 90
}
item {
  name : "TBD66"
  id : 91
}
item {
  name : "TBD67"
  id : 92
}
item {
  name : "TBD68"
  id : 93
}
item {
  name : "TBD69"
  id : 94
}
item {
  name : "TBD70"
  id : 95
}
item {
  name : "TBD71"
  id : 96
}
item {
  name : "TBD72"
  id : 97
}
item {
  name : "TBD73"
  id : 98
}
item {
  name : "TBD74"
  id : 99
}
item {
  name : "TBD75"
  id : 100
}




